options:
  port:
    type: int
    default: 8675
    description: |
      Http port to serve requests on.
  bind_address:
    type: string
    default: 0.0.0.0
    description: |
      IP address to bind to. Defaults to all.
